version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: house31-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: house31admin
      MONGO_INITDB_ROOT_PASSWORD: house31password
      MONGO_INITDB_DATABASE: house31-website
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - house31-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    container_name: house31-backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGODB_URI: mongodb://house31admin:house31password@mongodb:27017/house31-website?authSource=admin
      MONGODB_DB_NAME: house31-website
      FRONTEND_URL: http://localhost:3000
      ADMIN_API_KEY: house31-admin-key-2024
      JWT_SECRET: your-development-jwt-secret-key
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - house31-network
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    container_name: house31-frontend
    restart: unless-stopped
    environment:
      VITE_API_BASE_URL: http://localhost:5000/api
      VITE_APP_TITLE: House31 Website
      DOCKER_ENV: true
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend
    networks:
      - house31-network
    stdin_open: true
    tty: true

volumes:
  mongodb_data:
    driver: local
  backend_node_modules:
    driver: local
  frontend_node_modules:
    driver: local

networks:
  house31-network:
    driver: bridge
